#!/usr/bin/env python3

import sys
from rqt_gui.main import Main
from hexapod_rqt.hexapod_controller import HexapodController

plugin = 'hexapod_rqt.hexapod_controller.HexapodController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))